# Generated by Django 2.2.6 on 2019-11-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
