# Generated by Django 2.2.6 on 2019-11-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_auto_20191104_0153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
    ]
