# Generated by Django 2.2.6 on 2019-11-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
