# Generated by Django 2.2.6 on 2019-10-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=128, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='bannerpage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Title'),
        ),
    ]
