# Generated by Django 2.2.6 on 2019-10-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SocialMediaSettings",
            new_name="SocialMedia",
        ),
        migrations.AlterModelOptions(
            name="socialmedia",
            options={"verbose_name": "Social Media"},
        ),
    ]
