# Generated by Django 2.2.6 on 2019-10-26 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0008_auto_20191024_2344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleanalytics",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Google Analytics Tracking ID.",
                        regex="^[uU][aA]-\\d{4,9}-\\d{1,4}$",
                    )
                ],
                verbose_name="Tracking ID",
            ),
        ),
    ]
