# Generated by Django 2.2.6 on 2019-11-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0010_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Subscription"},
        ),
    ]
