# Generated by Django 2.2.6 on 2019-11-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_auto_20191109_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='telegram_invite_link',
            field=models.URLField(blank=True, verbose_name='Invite Link'),
        ),
    ]
