# Generated by Django 2.2.6 on 2019-11-02 23:03

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations

import streams.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0002_auto_20191102_2347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "title_and_text",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock(required=True)),
                                ("text", wagtail.core.blocks.TextBlock(required=True)),
                            ]
                        ),
                    ),
                    ("rich_text", streams.blocks.RichTextBlock()),
                    ("simple_rich_text", streams.blocks.SimpleRichTextBlock()),
                    (
                        "cards",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock(required=True)),
                                (
                                    "subtitle",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "cards",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.core.blocks.CharBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.core.blocks.TextBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "page",
                                                    wagtail.core.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.core.blocks.URLBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
