# Generated by Django 2.2.6 on 2019-11-08 21:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_newslettersubscription_subscriptionpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="uuid",
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=128),
        ),
    ]
