# Generated by Django 2.2.6 on 2019-11-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0007_auto_20191109_2334"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionpage",
            old_name="success_text",
            new_name="email_success_text",
        ),
    ]
