# Generated by Django 2.2.6 on 2019-10-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191019_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(max_length=128),
        ),
    ]
