# Generated by Django 2.2.6 on 2019-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191019_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
