# Generated by Django 2.2.6 on 2019-10-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': 'Blog Author', 'verbose_name_plural': 'Blog Authors'},
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogAuthor'),
        ),
    ]
