# Generated by Django 2.2.6 on 2019-10-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191023_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='subtitle',
        ),
    ]
