# Generated by Django 2.2.6 on 2020-01-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191231_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='notify_email_subscribers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='notify_telegram_subscribers',
            field=models.BooleanField(default=False),
        ),
    ]
